typography_spectrum: 0.16836903233966322
color:
  brandStrength: 0.08919192349123262
  lightness: 0.6206965058994027
  saturation: 0.4313075133227734
  rhythmicContrast: 0.9832972057285433
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
github: true
layout_spectrum: 0.07976222811386653
name: 'Tobiere Consulting Group '
navigation:
  - name: Portfolio
    id: dab223d0-c6d9-4c14-a4e3-13345099a334
    type: content
  - name: The Group
    id: 129b847a-cd0b-4e3c-8d84-7157ee4d0e67
    type: content
title: Innovative Application of Cloud Services Creating Efficiency in the Workspace
content: []
description: Service Disabled Woman Owned Small Business (SDWOSB)
purpose:
  - type: contact
    url: 'mailto:dtobiere@tobiereconsultgroup.com'
    label: Contact the Group
