typography_spectrum: 0.16836903233966322
color:
  brandStrength: 0.08919192349123262
  lightness: 0.6206965058994027
  saturation: 0.4313075133227734
  rhythmicContrast: 0.9832972057285433
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
github: true
layout_spectrum: 0.07976222811386653
name: Tobiere Consulting Group (TCG)
navigation:
  - name: The Group
    id: 93b6b05f-706e-49a9-a003-e5b104351326
    type: content
  - name: Prepared
    id: dab223d0-c6d9-4c14-a4e3-13345099a334
    type: content
title: Innovative Application of Cloud Services to create Efficiency in the Workspace
content: []
description: Service Disabled Woman Owned Small Business (SDWOSB)
purpose:
  - type: contact
    url: 'mailto:dtobiere@tobiereconsultgroup.com'
    label: Contact the Group
